// src/my-react-component/index.js
import React from 'react';
import AddComponent from '../my-add-component';

class MyAddComponent extends React.Component {
    constructor(props) {
        super(props);
        this.name = this.props.name;
        this.time = this.props.time
    }
    init () {
        const demoComponent = Object.create(AddComponent({name: 'MyAddComponent'})).initCom();
        return demoComponent.renderCom.call(this, demoComponent, React);
    }
    render () {
        // return <div>Hello {this.props.name}</div>;
        return this.init();
    }
}

export default MyAddComponent;

// src/my-component/my-component.vue
<template>
	<div>
		<div>My vue component</div>
		<div>Vue Num:&nbsp;{{vueNum}}</div>
		<button @click="add">Vue VDOM '+' Btn</button>
		<div>-------My-Common-Addcomponent In Vue Component↓--------</div>
		<my-snabb-component
			:name="'mySetPropName'"
			:time="30"
			@addCb="addCbFn"
		></my-snabb-component>
	</div>
</template>

<script>
import DemoComponent from '../my-snabb-component';
import AddComponent from '../my-add-component';
export default {
    name: 'MyComponent',
	data () {
        return {
            vueNum: 0
        };
	},
	components: {
        /*'my-snabb-component': (resolve) => {
            const snabbDom =  DemoComponent({
                name: 'My Snabbdom',
                type: 3,
                num: 1
            });
            resolve(
                {
                    template: snabbDom
                }
            );
        }*/
        /*'my-snabb-component': {
            render (createElement) {
                const snabbDom = DemoComponent({
                    name: 'My Snabbdom',
                    type: 3,
                    num: 1
                }, 'vue');
                console.log('-----', snabbDom);
                return createElement(snabbDom.sel, snabbDom.data.props, snabbDom.children);
            }
        }*/
        /*'my-snabb-component': {
            data () {
                return {
                    testNum: 10
                };
            },
	        created () {
                this.testNum = 20;
	        },
	        mounted () {
                this.testNum = 30;
	        },
	        methods: {
                add () {
                    this.testNum++;
                    console.log('this.testNum', this.testNum);
                }
	        },
            render (h) {
                const snabbDom = DemoComponent({
                    name: 'My Snabbdom',
                    type: 3,
                    num: this.testNum
                }, h, this);
                console.log('------', snabbDom);
                return snabbDom
            }
        }*/
        'my-snabb-component': (resolve) => {
            const demoComponent = Object.create(AddComponent({name: 'MyAddComponent'})).initCom(); // Auto Init component
            // demoComponent.methods.add = function () { // This add function will replace component's default 'add' function
            //     this.num = this.num + 10;
            // };
            console.log('demoComponent:', demoComponent);
            resolve({
	            ...demoComponent,
                render (h) { // If data are changed in component that component will render again
                    return demoComponent.renderCom.call(this, demoComponent, h);
                }
            });
        }
	},
	methods: {
        add () {
            this.vueNum = this.vueNum + 1;
        },
        addCbFn (val) {
            console.log('addCbFn:', val);
        }
	}
}
</script>

<style scoped>

</style>
